### ISSUE TITLE
TypeError: Cannot read property 'transformFile' of undefined

### ISSUE THREAD

**Issue by ExoMemphiz** [javascript-obfuscator/react-native-obfuscating-transformer#16]
**Versions**:

"react-native": "0.59.10",
"react-native-obfuscating-transformer": "^1.0.0",

**Files**:

metro.config.js:

```js
module.exports = {
    transformer: {
        babelTransformerPath: require.resolve("./transformer"),
        getTransformOptions: async () => ({
            transform: {
                experimentalImportSupport: false,
                inlineRequires: false,
            },
        }),
    },
};
```

transformer.js:

```js
const obfuscatingTransformer = require('react-native-obfuscating-transformer')

module.exports = obfuscatingTransformer({})
```

**Error I am getting:**

```sh
Loading dependency graph, done.
Loading dependency graph...error Cannot read property 'transformFile' of undefined
debug TypeError: Cannot read property 'transformFile' of undefined
    at /home/chris/Documents/JSObfuscation/ObfuscationTest/node_modules/metro/src/Bundler.js:83:34
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/chris/Documents/JSObfuscation/ObfuscationTest/node_modules/metro/src/Bundler.js:14:24)
    at _next (/home/chris/Documents/JSObfuscation/ObfuscationTest/node_modules/metro/src/Bundler.js:34:9)
```

**Repo**

Simplest repo I could make that reproduces this error:

[https://github.com/ExoMemphiz/ObfuscationTest/](https://github.com/ExoMemphiz/ObfuscationTest/)

**Comment by ExoMemphiz** [comment]
Alright, I got slightly further with a different repo that I found that used this library.

I needed to add these lines of code to the getMetroTransformer.js file:

```js
const metroVersion = semver(require('metro/package.json').version).minor;
if (metroVersion >= 51) {
  return require('metro-react-native-babel-transformer/src/index');
}
```

And of course have the metro-react-native-babel-transformer installed, as well as having this .babelrc file:

```js
{
  "presets": ["module:metro-react-native-babel-preset"]
}
```

It seems to work (Tried react-native v0.57.0 currently), but minification happens on the bundle, after obfuscating, which I think is the reason that the output is basically the same, if I obfuscate or not.

I get this in the log when I run the ./gradlew assembleRelease

```
> Task :app:bundleReleaseJsAndAssets
warning: the transform cache was reset.
Loading dependency graph, done.
transform[stdout]: src/App.js
transform[stdout]: Obfuscating src/App.js
info Writing bundle output to:, .../index.android.bundle
info Done writing bundle output
```

Which should mean it actually obfuscates the code, unfortunately it is not shown in the output bundle itself. Also the selfDefending option breaks the app, I assume because of the above reason - minifying the output changes the code, and thus breaks the selfDefending code.

Any way to keep the obfuscated code, while bundling it?

**Comment by mrcarjul** [comment]
I have the same issue, did you managed to solve it?

**Comment by jamal-rahimzadegan** [comment]
same here

**Comment by anhdevit** [comment]
Can every one give me the solution?

**Comment by anhdevit** [comment]
I find the solution when using with react-native 0.61
This is my metro.config.js
My problem disappear when I change babelTransformerPath: require.resolve("./transformer") to getTransformModulePath: () => {
      return require.resolve('./transformer');
    },
```
module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
    getTransformModulePath: () => {
      return require.resolve('./transformer');
    },
  },
};
```

**Comment by Ahsan123-design** [comment]
> I find the solution when using with react-native 0.61
> This is my metro.config.js
> My problem disappear when I change babelTransformerPath: require.resolve("./transformer") to getTransformModulePath: () => {
> return require.resolve('./transformer');
> },
> 
> ```
> module.exports = {
>   transformer: {
>     getTransformOptions: async () => ({
>       transform: {
>         experimentalImportSupport: false,
>         inlineRequires: false,
>       },
>     }),
>     getTransformModulePath: () => {
>       return require.resolve('./transformer');
>     },
>   },
> };
> ```

yes this issue has been resolved for this Solution.
thanks a lot man.

**Comment by timorss** [comment]
npm i babylon --save-dev
