### ISSUE TITLE
Error when running in debug mode

### ISSUE THREAD

**Issue by vuphuctho** [javascript-obfuscator/react-native-obfuscating-transformer#4]
** Project dependencies **
- react-native 0.51.0
- react-native-obfuscating-transformer ^1.0.0-rc.0

** Problem details **
- Add two files with info shown in [Usage](https://github.com/javascript-obfuscator/react-native-obfuscating-transformer#usage)
- run react-native run-ios to start app in debug mode

** Observation **
Following error was thrown in console:

```
Bundling `index.js`  [development, non-minified]  0.0% (0/952), failed.
error: bundling failed: Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
    at SourceMapGenerator_validateMapping [as _validateMapping] (/Users/tblaziken/Documents/TSP/mahb-rn/node_modules/react-native-obfuscating-transformer/node_modules/source-map/lib/source-map-generator.js:276:15)
    at SourceMapGenerator_addMapping [as addMapping] (/Users/tblaziken/Documents/TSP/mahb-rn/node_modules/react-native-obfuscating-transformer/node_modules/source-map/lib/source-map-generator.js:110:12)
    at /Users/tblaziken/Documents/TSP/mahb-rn/node_modules/react-native-obfuscating-transformer/dist/composeSourceMaps.js:9:19
    at Array.forEach (<anonymous>)
    at Object.convertMetroRawSourceMapToStandardSourceMap (/Users/tblaziken/Documents/TSP/mahb-rn/node_modules/react-native-obfuscating-transformer/dist/composeSourceMaps.js:7:9)
    at Object.obfuscateCodePreservingSourceMap (/Users/tblaziken/Documents/TSP/mahb-rn/node_modules/react-native-obfuscating-transformer/dist/obfuscateCode.js:17:35)
    at Object.transform (/Users/tblaziken/Documents/TSP/mahb-rn/node_modules/react-native-obfuscating-transformer/dist/obfuscatingTransformer.js:72:96)
    at asyncify (/Users/tblaziken/Documents/TSP/mahb-rn/node_modules/metro-bundler/src/JSTransformer/worker/index.js:114:35)
    at /Users/tblaziken/Documents/TSP/mahb-rn/node_modules/async/asyncify.js:82:27
```

**Comment by vuphuctho** [comment]
My temporary fix is to put a check in `rn-cli.config.js`. This works, but I expect an official fix for this.

```
if (process.env.NODE_ENV === 'production') {
  module.exports = {
    getTransformModulePath() {
      return require.resolve("./transformer")
    },
  }
}
```

**Comment by ds300** [comment]
Hi :heart: :wave:

Which version of source-map do you have? run this command and paste the output here:

    cat node_modules/source-map/package.json | grep version

**Comment by vuphuctho** [comment]
```
  "version": "0.5.7"
```
